import streamlit as st

st.set_page_config(
    page_title="My Streamlit App",
    page_icon="🧊",
    layout="wide",
    initial_sidebar_state="expanded",
    # The following are not directly related to themes, but are common in set_page_config
)


# Programmatic Theme adjustments (limited compared to config.toml)
st.markdown(
    """
    <style>
    body {
        color: #0072cd;  /* Text color */
        background-color: #d9d9d9; /* Background color */
    }
    .streamlit-button {
        background-color: #0072ce !important; /* Primary color for buttons */
        color: white !important;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


# ... rest of your Streamlit app code
